---
name: Start FreeBSD Vagrant Box
description: Allow running command-line programs via bash shell of FreeBSD VMs provisioned with Vagrant using the run keyword.

inputs:
  boot_timeout:
    default: 1800
    description: VM Boot Timeout
    type: string
  box:
    default: generic/freebsd14
    description: Vagrant Box
    type: string
  connect_timeout:
    default: 30
    description: VM SSH Connect Timeout
    type: string
  cpus:
    default: 2
    description: VM CPUs
    options:
      - 2
      - 4
      - 8
    type: choice
  memory:
    default: 2048
    description: VM Memory
    options:
      - 1024
      - 2048
      - 4096
      - 8192
    type: choice
  pre_package_commands:
    default: >-
      find ${{ github.workspace }} -mindepth 1 -delete;
      find ${{ runner.temp }} -mindepth 1 -delete;
      sudo pkg clean --all --yes;
    description: Command(s) to run before packaging Vagrant Box (double quotation marks are not allowed)
    type: string
  provider:
    description: Vagrant provider to use, defaults to virtualbox
    default: virtualbox
    options:
      - libvirt
      - virtualbox
    type: choice
  provision_commands:
    default: >-
      sysrc update_motd=NO;
      service motd onestop;
      rm -f /var/run/motd;
      chmod -x /usr/bin/fortune;
      export ASSUME_ALWAYS_YES=yes;
      pkg bootstrap -f;
      pkg upgrade;
      pkg install bash rsync;
      echo 'AcceptEnv *' >> /etc/ssh/sshd_config;
      service sshd restart;
      mkdir -p ${{ github.workspace }};
      chown vagrant:vagrant ${{ github.workspace }};
      mkdir -p ${{ runner.temp }};
      chown vagrant:vagrant ${{ runner.temp }};
    description: Command(s) to run for provisioning (double quotation marks are not allowed)
    type: string
  save_box_to_cache:
    description: Save Vagrant Box to GitHub Actions Cache
    type: boolean
  use_cached_box:
    description: Use Vagrant Box from GitHub Actions Cache
    type: boolean
  vagrant_box_descriptor:
    default: /tmp/packaged.box
    description: Vagrant Box Descriptor <name, url, or path>
    type: string
  vagrant_ssh_username:
    default: vagrant
    description: SSH Username for `vagrant ssh`
    type: string


runs:
  using: composite
  steps:
    - name: Start FreeBSD Vagrant Box
      uses: hummeltech/vagrant-action@v2
      with:
        boot_timeout: ${{ inputs.boot_timeout }}
        box: ${{ inputs.box }}
        connect_timeout: ${{ inputs.connect_timeout }}
        cpus: ${{ inputs.cpus }}
        memory: ${{ inputs.memory }}
        pre_package_commands: ${{ inputs.pre_package_commands }}
        provider: ${{ inputs.provider }}
        provision_commands: ${{ inputs.provision_commands }}
        save_box_to_cache: ${{ inputs.save_box_to_cache }}
        use_cached_box: ${{ inputs.use_cached_box }}
        vagrant_box_descriptor: ${{ inputs.vagrant_box_descriptor }}
        vagrant_ssh_username: ${{ inputs.vagrant_ssh_username }}

